DEFINE_ACTION_FUNCTION fix_bgee_26
BEGIN
  // Fix broken Tremain/Casson Raise Dead scene

  LAUNCH_ACTION_FUNCTION install
    STR_VAR
    file	= "tremain.baf"
    location	= "scripts"
  END


  // Fix endless recurring animation from Yeslick's innate Dispel Magic

  LAUNCH_ACTION_FUNCTION edit_spell
    STR_VAR
    spell	= "spin112"
    editstring	= ~delete_effect=>"opcode = 215 and timing = 1"~
  END
END	// fix_bgee_26


